[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

# [colors.search.footer_bar]
# background = "#A6ADC8"
# foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
y = 16

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002d"
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = """
lf
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = """
l
"""
key = "D"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B[A
"""
key = "R"
mods = "Command|Shift"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.padding]
x = 6
y = 6
