#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
yabai -m signal --add event=window_created action="sketchybar -m --trigger windows_on_spaces &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger windows_on_spaces &> /dev/null"

yabai -m config external_bar all:32:0

# window
yabai -m config window_origin_display           default
yabai -m config window_placement                second_child
yabai -m config window_zoom_persist             on
yabai -m config window_animation_duration       0.0
yabai -m config window_animation_frame_rate     120
yabai -m config window_opacity_duration         0.0
yabai -m config insert_feedback_color           0xffd75f5f
yabai -m config window_shadow                   float
yabai -m config active_window_opacity           1.0
yabai -m config normal_window_opacity           1.0
yabai -m config window_opacity_duration         0.0
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    off

# mouse
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             autofocus
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config mouse_drop_action               swap

# general space settings
yabai -m config top_padding                  0
yabai -m config bottom_padding               2
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   2

# # Spaces
# yabai -m space 1
# yabai -m space 2
# yabai -m space 3
# yabai -m space 4
# yabai -m space 5
# yabai -m space 6
# yabai -m space 7
# yabai -m space 8
# yabai -m space 9
# yabai -m space 10


# specific space settings
yabai -m config --space 4  layout           stack

# free floating windows
yabai -m config --space 6  layout           float
yabai -m config --space 10 layout           float

# Browsers
yabai -m rule --add app="^Google Chrome$"   space=2
yabai -m rule --add app="^Safari$"          space=6
yabai -m rule --add app="Arc$"              space=6

# text editors
yabai -m rule --add app="^Sublime Text$"    space=3
yabai -m rule --add app="^Code$"            space=3

# IDE's
yabai -m rule --add app="^PhpStorm$"        space=4
yabai -m rule --add app="^GoLand$"          space=4
yabai -m rule --add app="^Android Studio$"  space=4


#database
yabai -m rule --add app="^TablePlus$"       space=5

yabai -m rule --add app="^Slack$"           space=7

yabai -m rule --add app="^GitHub Desktop$"  space=8

yabai -m rule --add app="^Spark$"           space=9
yabai -m rule --add app="^Edison Mail$"     space=9

# ignore apps
ignoreApps="^(Podcasts|Books|System Settings|Keychain Access|Reminders|TickTick|Raycast|AppCleaner|System Preferences|Karabiner-Elements|Karabiner-EventViewer|Finder|Alfred Preferences|Disk Utility|System Information|Activity Monitor|Path Finder|Docker Desktop|App Store)$"
yabai -m rule --add app="${ignoreApps}" manage=off
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# Some Goland settings, in case you are using it. float Goland Preference panes
JetBrainsApp='^(IntelliJ IDEA|WebStorm|GoLand|PhpStorm|Android Studio)$'
yabai -m rule --add app="${JetBrainsApp}" manage=off
yabai -m rule --add app="${JetBrainsApp}" title="( – )"  manage=on

yabai -m config layout                       bsp

echo "yabai configuration loaded.."
